name: SilvertownInspector
options:
  bundleIdPrefix: uk.co.infratec
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  SilvertownInspector:
    type: application
    platform: iOS
    sources:
      - SilvertownInspector
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: uk.co.infratec.silvertown-inspector
        INFOPLIST_FILE: SilvertownInspector/Info.plist
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSCameraUsageDescription: "Camera access is needed to take photos during inspections"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Photo library access is needed to attach existing photos to inspections"
        SWIFT_EMIT_LOC_STRINGS: YES
        TARGETED_DEVICE_FAMILY: "1,2"
    entitlements:
      path: SilvertownInspector/SilvertownInspector.entitlements
      properties:
        com.apple.security.app-sandbox: false
